---
# Use manual composer require tasks until Ansible 2.10.4 is released.
- name: Ensure Drush is installed globally via Composer.
  command: "{{ composer_path }} global require drush/drush:{{ drush_composer_version }} "
  register: drush_composer_require
  changed_when: "'Nothing to install' not in drush_composer_require.stdout"
  with_items: "{{ drupal_composer_dependencies|default([]) }}"

# Switch back to this task after Ansible 2.10.4 is released.
# - name: Ensure Drush is installed globally via Composer.
#   composer:
#     command: require
#     global_command: true
#     arguments: "drush/drush:{{ drush_composer_version }}"
#   register: drush_composer_require

- name: Update global Drush install if configured.
  composer:
    command: update
    global_command: true
    arguments: "drush/drush --with-dependencies"
  when:
    - drush_composer_update
    - not drush_composer_require.changed
  tags: ['skip_ansible_lint']

- name: Ensure globally-installed Drush is symlinked into bin dir.
  file:  # noqa 208
    src: "{{ drush_composer_global_bin_path }}/drush"
    dest: "{{ drush_composer_path }}"
    state: link
