---
- include: install-drush-launcher.yml
  when: drush_launcher_install

- include: install-drush-composer.yml
  when: drush_composer_global_install

- include: source-install.yml
  when: drush_install_from_source and drush_version|version_compare('9.0', '<')
